### ISSUE TITLE
Skrypt wyrzuca błąd, chociaż nie zmieniałem nic w konfiguracji

### ISSUE THREAD

**Issue by kamiKAC** [slawekmikula/epguide#46]
Witam

Wiem, że skrypt nie jest już rozwijany, jednak od dawna go używam i przesta działać bez poważnego powodu. Raczej nic nie aktualizowałem i z dnia na dzień mam taki komunikat przy próbie odpalenia skryptu (opcja --configure daje ten sam błąd tylko w pierwszej linii)

```
sudo su mythtv -c "/usr/local/bin/tv_grab_pl_epguide --config-file=/home/mythtv/.mythtv/DVB-T.xmltv"
Traceback (most recent call last):
  File "/usr/local/bin/tv_grab_pl_epguide", line 9, in <module>
    load_entry_point('epguide==1.9.3', 'console_scripts', 'tv_grab_pl_epguide')()
  File "/usr/local/lib/python2.7/dist-packages/epguide-1.9.3-py2.7.egg/epguide/tv_grab_pl_epguide.py", line 245, in RunTvGrabPlEpguide
    return grabber.run()
  File "/usr/local/lib/python2.7/dist-packages/epguide-1.9.3-py2.7.egg/epguide/tv_grab_pl_epguide.py", line 240, in run
    return self.normal_run()
  File "/usr/local/lib/python2.7/dist-packages/epguide-1.9.3-py2.7.egg/epguide/tv_grab_pl_epguide.py", line 164, in normal_run
    self.tv_grab_config_obj = ConfigObj(self.tv_grab_options.config_file)
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
```

A to początek mojego configu:
```

#channel  ID ID
#channel 13-Ulica 13 Ulica
channel ATM-Rozrywka ATM Rozrywka
#channel AXN AXN
#channel AXN-Black AXN Black

```
Próbowałem reinstalować pythona i jego pakiety (Ubuntu 16.04.06 LTS), ale nic to nie zmienia.
Będę wdzięczny za wszelką pomoc, bo kompletnie nie znam pythona.

**Comment by slawekmikula** [comment]
To bardzo dobra okazja, aby zdobyć trochę wiedzy o tym języku. Spróbuj ! Np. tutaj: https://docs.python.org/3/tutorial/index.html

Błąd wygląda na błąd konfiguracji. Sprawdź plik konfiguracji, edytuj go sprawdzając co nie gra. To najprostsze rozwiązanie.

Wybacz, ale zamknę to zgłoszenie, gdyż nie będzie rozwiązywane inaczej niż ten komentarz. Powodzenia !
